package io.github.astiskala.minimpos.app.data.db

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Relation
import io.github.astiskala.minimpos.core.money.PaymentContext

/** Confirmed history purge awaiting its non-secret destination settings write; singleton recovery journal. */
@Entity(tableName = "history_switch")
data class HistorySwitchEntity(
    /** Singleton key, always 1. */
    @PrimaryKey val id: Int = 1,
    /** Current TerminalSettings JSON with no credentials. */
    val terminalJson: String,
)

/**
 * A tax rate products can use (table `tax_rates`), managed in Settings › Tax.
 *
 * At least one rate always exists: the starter rates of the device's country (always including a 0% rate) are seeded
 * on first launch, and the last one cannot be deleted. A rate cannot be deleted either while products use it (the
 * products' foreign key is `RESTRICT`). Sales copy the name and rate onto their lines, so editing a rate never changes
 * past receipts.
 *
 * @property id Row ID generated by Room; 0 for a rate that has not been inserted yet.
 * @property name Label printed on receipts and in the tax breakdown, such as "GST 10%" or "No tax".
 * @property rateMilliPercent The rate in thousandths of a percent: 10% is 10_000 and 0 marks a zero rate.
 * @property sortOrder Position in lists (ascending); ties are ordered by highest rate first, then by name.
 */
@Entity(tableName = "tax_rates")
data class TaxRateEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val rateMilliPercent: Int,
    val sortOrder: Int = 0,
)

/**
 * A product category (table `categories`) used to group the tiles on the sale screen.
 *
 * Deleting a category keeps its products: their `categoryId` becomes null (foreign key `SET NULL`).
 *
 * @property id Row ID generated by Room; 0 for a category that has not been inserted yet.
 * @property name Display name; catalogue imports match existing categories by name, ignoring case.
 * @property sortOrder Position in lists (ascending); ties are ordered by name.
 * @property sample Whether this category was added as removable sample data.
 */
@Entity(tableName = "categories")
data class CategoryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val sortOrder: Int = 0,
    @ColumnInfo(defaultValue = "0") val sample: Boolean = false,
)

/** What a payment is, and so which products it sells; stored by name in `products.kind` and `sales.kind`. */
enum class SaleKind {
    /** A normal sale: any number of sale products and custom items, charged (and captured) straight away. */
    SALE,

    /**
     * A pre-authorisation: one pre-authorisation product or custom amount, only held on the card. It is captured (or
     * what it holds adjusted) through Adyen's Checkout API, or cancelled from history; it can be refunded only once
     * captured, up to the amount captured.
     */
    PRE_AUTHORISATION,
    ;

    /**
     * Whether a payment of this kind holds a single item with a quantity of one, so adding a product or custom item
     * replaces the cart: a pre-authorisation.
     */
    val singleItem: Boolean get() = this == PRE_AUTHORISATION
}

/**
 * A product in the catalogue (table `products`).
 *
 * Every product has a tax rate. Untaxed products use a 0% rate; sales and pre-authorisations have separate products.
 *
 * @property id Row ID generated by Room; 0 for a product that has not been inserted yet.
 * @property name Name shown on the tile, the cart and receipts.
 * @property priceMinor Unit price in minor units of the configured currency. Whether it includes tax depends on
 * [io.github.astiskala.minimpos.app.data.settings.PaymentSettings.taxMode].
 * @property taxRateId The [TaxRateEntity] applied to this product. Every product has one; products without tax use a 0%
 * rate such as "No tax". The rate is kept while "Charge tax" is off, so it applies again when tax is switched back
 * on.
 * @property categoryId The [CategoryEntity] the product is listed under, or null when it is uncategorised.
 * @property sku Optional stock-keeping unit or barcode value, used by barcode scanning and to match products when a
 * catalogue is merged. Non-blank SKUs are unique across both payment kinds.
 * @property sortOrder Position in lists (ascending); ties are ordered by name, ignoring case.
 * @property kind Whether the product is sold in a sale or taken as a pre-authorisation; each kind is only offered on its
 * own screen (New sale or Pre-authorise).
 * @property sample Whether this product was added as removable sample data, including after edits.
 */
@Entity(
    tableName = "products",
    foreignKeys = [
        ForeignKey(entity = TaxRateEntity::class, parentColumns = ["id"], childColumns = ["taxRateId"], onDelete = ForeignKey.RESTRICT),
        ForeignKey(entity = CategoryEntity::class, parentColumns = ["id"], childColumns = ["categoryId"], onDelete = ForeignKey.SET_NULL),
    ],
    indices = [Index("taxRateId"), Index("categoryId"), Index(value = ["sku"], unique = true)],
)
data class ProductEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val priceMinor: Long,
    val taxRateId: Long,
    val categoryId: Long? = null,
    val sku: String? = null,
    val sortOrder: Int = 0,
    @ColumnInfo(defaultValue = "SALE") val kind: SaleKind = SaleKind.SALE,
    @ColumnInfo(defaultValue = "0") val sample: Boolean = false,
)

/** Latest catalog import receipt, written in the same transaction as the imported rows.
 * @property id Singleton row ID; always 1.
 * @property transferId Verified import journal identity, used to avoid replaying a completed catalog write.
 * @property productsAdded Count of inserted products.
 * @property productsUpdated Count of updated products.
 * @property taxRatesAdded Count of inserted tax rates.
 * @property categoriesAdded Count of inserted categories.
 */
@Entity(tableName = "catalog_import")
data class CatalogImportEntity(
    @PrimaryKey val id: Int = 1,
    val transferId: String,
    val productsAdded: Int,
    val productsUpdated: Int,
    val taxRatesAdded: Int,
    val categoriesAdded: Int,
)

/** Where a sale is in its lifecycle; stored by name in `sales.status`. */
enum class SaleStatus {
    /** Written before the terminal is called. A sale still PENDING at the next app start was interrupted. */
    PENDING,

    /** The terminal approved the payment. Only approved sales can be refunded. */
    APPROVED,

    /**
     * The terminal answered that the payment did not succeed for a reason other than a cancellation, such as a refusal
     * or `Busy`; `errorCondition` and `refusalReason` say why.
     */
    DECLINED,

    /** The payment was cancelled or aborted on the terminal (ErrorCondition `Cancel` or `Aborted`). */
    CANCELLED,

    /**
     * The payment never took effect, so nothing was charged: for example the terminal is not set up, or the request
     * was not processed.
     */
    FAILED,

    /**
     * The outcome could not be established: no answer even after the transaction status checks, or the app stopped
     * mid-payment. Staff can check it again from history with a TransactionStatus request (for a payment link, by
     * creating it again with the same idempotency key, which returns the link made the first time).
     */
    UNKNOWN,

    /** A payment link was created for the sale ([SaleEntity.paymentLink]) and has not been paid yet. Added in version 9. */
    AWAITING_PAYMENT,

    /** The sale's payment link stopped working before it was paid, so nothing was charged. Added in version 9. */
    EXPIRED,
}

/**
 * A card payment (table `sales`), with the cart totals as charged and what the terminal reported.
 *
 * The row is inserted as [SaleStatus.PENDING] before the terminal (or, for a [paymentLink], Adyen's Checkout API) is
 * called and updated with the outcome afterwards, so every payment attempt can be traced. The items are in
 * [SaleLineEntity]; refunds are in [RefundEntity]. All amounts are in minor units of [currency].
 */
@Entity(tableName = "sales", indices = [Index("createdAt"), Index("poiTransactionId")])
data class SaleEntity(
    /** Random UUID generated by the app. */
    @PrimaryKey val id: String,
    /** Read-only demo history added by sample setup, never a payment sent to a terminal. */
    @ColumnInfo(defaultValue = "0") val sample: Boolean = false,
    /** When the sale was started, in epoch milliseconds; history is ordered and pruned by it. */
    val createdAt: Long,
    /** ISO 4217 code of the currency charged. */
    val currency: String,
    /** Name of the [io.github.astiskala.minimpos.core.tax.TaxMode] the totals were calculated with (`INCLUSIVE` or `EXCLUSIVE`). */
    val taxMode: String,
    /** Total excluding tax. */
    val netMinor: Long,
    /** Total tax; 0 when "Charge tax" was off. */
    val taxMinor: Long,
    /** Amount charged to the card (net plus tax). */
    val totalMinor: Long,
    /** Lifecycle state; see [SaleStatus]. */
    val status: SaleStatus,
    /** The transaction reference sent to Adyen as the merchant reference, such as `260930-145811-VQ45`. */
    val merchantReference: String,
    /**
     * The operator-entered customer reference, sent as payment metadata. Only set when it is also the shopper
     * reference; null when the email is the shopper reference.
     */
    val customerReference: String? = null,
    /**
     * The shopper reference sent with the payment (or, with a [paymentLink], with the link), which saves the card under
     * it only when [tokenizationRequested]; null when none was sent.
     */
    val shopperReference: String? = null,
    /** The shopper's email captured at checkout, if any. */
    val shopperEmail: String? = null,
    /** Whether the shopper asked to save their card with this payment. */
    val tokenizationRequested: Boolean = false,
    /** Adyen's ID of the saved card, set when tokenization succeeded. */
    val storedPaymentMethodId: String? = null,
    /**
     * The nexo ServiceID of the payment request. Set just before the terminal is called; used to check the transaction
     * status when the outcome is unknown.
     */
    val serviceId: String? = null,
    /** POIID (`<model>-<serial>`) of the terminal the payment was sent to. */
    val poiId: String? = null,
    /** The terminal's POITransactionID, needed to refund the payment; refund QR codes are looked up by it. */
    val poiTransactionId: String? = null,
    /** The POITransactionID time stamp exactly as the terminal sent it, needed with [poiTransactionId] for refunds. */
    val poiTimestamp: String? = null,
    /** Adyen's PSP reference for the payment. */
    val pspReference: String? = null,
    /** The card brand as reported by the terminal. */
    val paymentBrand: String? = null,
    /** The masked card number as reported by the terminal. */
    val maskedPan: String? = null,
    /** How the card was read (for example tapped or inserted), as reported by the terminal. */
    val entryMode: String? = null,
    /** The issuer's approval code. */
    val authCode: String? = null,
    /** Why the sale did not succeed, as Adyen or the terminal worded it, for display; null when they did not say. */
    val message: String? = null,
    /**
     * JSON list of [io.github.astiskala.minimpos.core.receipt.CardReceiptLine] for the customer's card receipt;
     * null when none was sent.
     */
    val customerReceiptJson: String? = null,
    /**
     * JSON list of [io.github.astiskala.minimpos.core.receipt.CardReceiptLine] for the merchant's card receipt;
     * null when none was sent.
     */
    val cashierReceiptJson: String? = null,
    /** Whether the terminal asked for a signature, which makes the merchant copy necessary by default. */
    val signatureRequired: Boolean = false,
    /** Amount already refunded from this terminal, never more than [amountMinor]; cancellations do not count. */
    val refundedMinor: Long = 0,
    /** The address the receipt was last emailed to, or null if it has not been emailed. */
    val emailedTo: String? = null,
    /**
     * Terminal API `ErrorCondition` of an unsuccessful payment (such as `Refusal` or `Busy`), which decides whether a
     * retry can help. Added in database version 2.
     */
    val errorCondition: String? = null,
    /** Adyen's refusal reason of a declined payment. Added in database version 2. */
    val refusalReason: String? = null,
    /**
     * A sale, or a pre-authorisation that only held [totalMinor] (sent with `authorisationType=PreAuth` and manual
     * capture). Added in database version 5.
     */
    @ColumnInfo(defaultValue = "SALE") val kind: SaleKind = SaleKind.SALE,
    /**
     * Taken for tipping on the receipt: pre-authorised (`authorisationType=PreAuth`, manual capture) for [totalMinor],
     * printed with lines for a tip, and captured with the tip once it is entered. Added in database version 6.
     */
    @ColumnInfo(defaultValue = "0") val tipOnReceipt: Boolean = false,
    /** The tip written on the receipt; null while it is awaited (or for other sales), 0 for no tip. Added in version 6. */
    val tipMinor: Long? = null,
    /**
     * What the payment holds after authorisation adjustments; null while it was never adjusted, when [totalMinor] is
     * held. Added in database version 6.
     */
    val authorisedMinor: Long? = null,
    /** How the latest adjustment to [authorisedMinor] went; null before any. Added in database version 6. */
    val adjustment: AdjustmentStatus? = null,
    /**
     * Adyen's latest `adjustAuthorisationData` blob, from the payment response or the last synchronous adjustment;
     * null when the terminal sent none, so adjustments are asynchronous. Added in database version 6.
     */
    val adjustAuthorisationData: String? = null,
    /** The amount of the capture recorded by [captureStatus]; null before any. Added in database version 6. */
    val capturedMinor: Long? = null,
    /** Where the capture of a payment taken with manual capture stands; null before any. Added in database version 6. */
    val captureStatus: CaptureStatus? = null,
    /**
     * Why the latest capture or adjustment did not go through as Adyen worded it (for example the issuer refused a
     * higher amount), for display; null when it did, or Adyen did not say. Added in database version 6.
     */
    val modificationMessage: String? = null,
    /**
     * Adyen's `paymentMethodVariant` as the terminal reported it, such as `visa` or `mc_applepay` for a card in a mobile
     * wallet ([io.github.astiskala.minimpos.core.payment.PaymentMethods.wallet] reads it); null when it sent none, and for sales from
     * before database version 7.
     */
    val paymentMethodVariant: String? = null,
    /**
     * Whether the payment held its amount and its cancellation (a full reversal) was accepted, so nothing was charged.
     * A cancellation refunds nothing, so it leaves [refundedMinor] alone. Added in database version 8.
     */
    @ColumnInfo(defaultValue = "0") val holdCancelled: Boolean = false,
    /**
     * Whether the sale is paid through an Adyen payment link instead of on a terminal: no terminal details, no PSP
     * reference (Adyen only sends that in a webhook, which this app has no server for), so it is refunded in the Customer
     * Area. Added in database version 9.
     */
    @ColumnInfo(defaultValue = "0") val paymentLink: Boolean = false,
    /** Adyen's ID of the [paymentLink], such as `PL50C5F751CED39G71`, once it was created. Added in database version 9. */
    val paymentLinkId: String? = null,
    /** The address of the [paymentLink] the shopper opens, once it was created. Added in database version 9. */
    val paymentLinkUrl: String? = null,
    /**
     * When the [paymentLink] stops working, in epoch milliseconds; chosen when the sale is opened and sent with it.
     * Added in database version 9.
     */
    val paymentLinkExpiresAt: Long? = null,
    /**
     * Why the sale did not succeed when the app itself says so (not set up, outcome unknown, interrupted), worded on
     * screen in the current language next to [message]; null otherwise. Added in database version 10.
     */
    val reason: StoredReason? = null,
    /**
     * Why the latest capture or adjustment did not go through when the app itself says so, worded on screen next to
     * [modificationMessage]; null otherwise. Added in database version 10.
     */
    val modificationReason: StoredReason? = null,
    /** The connection that sent the payment; null before sending. */
    val context: PaymentContext? = null,
    /** Frozen payment-page language, or null for Adyen's default. */
    val linkLocale: String? = null,
    /** Frozen country code used to create the payment link; null for none. */
    val linkCountry: String? = null,
    /** Frozen recurring model used to create the payment link; null when no card is saved. */
    val linkRecurringModel: String? = null,
    /** Identity of the latest adjustment, persisted before sending; null before any. */
    val adjustmentKey: String? = null,
    /** Amount of that adjustment in minor units; null before any. */
    val adjustmentAmountMinor: Long? = null,
    /** An adjustment was sent but its outcome remains unresolved. */
    val adjustmentPending: Boolean = false,
    /** Original terminal approval time in epoch milliseconds; null when not approved or its date is unavailable. */
    val processedAt: Long? = null,
    /** First send time of the current logical capture in epoch milliseconds; retained across retries. */
    val captureStartedAt: Long? = null,
    /** Time capture acceptance was recorded, in epoch milliseconds; null without dated acceptance. */
    val captureProcessedAt: Long? = null,
) {
    /** What the payment holds on the card: [authorisedMinor] after an adjustment, else [totalMinor]. */
    val heldMinor: Long get() = authorisedMinor ?: totalMinor

    /**
     * Whether the payment was taken with manual capture, so it only held its amount until captured: a
     * pre-authorisation, or a sale taken for tipping on the receipt.
     */
    val manualCapture: Boolean get() = kind == SaleKind.PRE_AUTHORISATION || tipOnReceipt

    /**
     * The payment's amount as it stands: the capture's once captured ([CaptureStatus.captured]), else the bill plus any
     * tip entered, else what a pre-authorisation holds, else [totalMinor].
     */
    val amountMinor: Long
        get() =
            when {
                captureStatus?.captured == true -> capturedMinor ?: totalMinor
                tipMinor != null -> totalMinor + tipMinor
                kind == SaleKind.PRE_AUTHORISATION -> heldMinor
                else -> totalMinor
            }
}

/** How the latest authorisation adjustment of a payment went; stored by name in `sales.adjustment`. */
enum class AdjustmentStatus {
    /** Adjusted synchronously: Adyen confirmed that the new amount is authorised. */
    AUTHORISED,

    /** Adjusted asynchronously: Adyen received the request and confirms the outcome only in the Customer Area. */
    REQUESTED,
}

/** Where the capture of a payment taken with manual capture stands; stored by name in `sales.captureStatus`. */
enum class CaptureStatus {
    /** Written before the Checkout API is called. A capture still PENDING at the next app start was interrupted. */
    PENDING,

    /** Adyen received the capture request; it confirms the capture only in the Customer Area. */
    REQUESTED,

    /** Adyen did not take the capture request, so nothing was captured; it can be sent again. */
    FAILED,

    /** It is not known whether Adyen received the request; sending it again is safe (same idempotency key). */
    UNKNOWN,
    ;

    /**
     * Whether the capture counts as made, so the payment counts as charged: Adyen received it ([REQUESTED]).
     * The one rule behind [SaleEntity.amountMinor] and
     * [io.github.astiskala.minimpos.app.refund.PaymentStanding.captured].
     */
    val captured: Boolean get() = this == REQUESTED
}

/**
 * One item of a sale (table `sale_lines`), frozen as sold so receipts and refunds do not change when the catalogue
 * does. Lines are deleted with their sale (foreign key `CASCADE`). All amounts are in minor units of the sale's
 * currency.
 *
 * @property id Row ID generated by Room; refunds refer to lines by it.
 * @property saleId The [SaleEntity] the line belongs to.
 * @property position Zero-based position in the cart, which is the order on receipts.
 * @property productId The catalogue product sold, or null for a custom item. It is not a foreign key, so it can point
 * to a product that has since been deleted.
 * @property name Item name as sold.
 * @property sku SKU as sold, if the product had one.
 * @property unitPriceMinor Unit price as entered (tax-inclusive or exclusive according to the sale's tax mode).
 * @property quantity Number of units sold.
 * @property taxName Name of the tax rate applied, as it was at the time of the sale.
 * @property taxRateMilliPercent The tax rate applied, in thousandths of a percent (10% is 10_000).
 * @property netMinor Line total excluding tax.
 * @property taxMinor Tax on the line.
 * @property grossMinor Line total including tax.
 * @property refundedQuantity Units already refunded from this terminal, never more than [quantity].
 */
@Entity(
    tableName = "sale_lines",
    foreignKeys = [
        ForeignKey(
            entity = SaleEntity::class,
            parentColumns = ["id"],
            childColumns = ["saleId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("saleId")],
)
data class SaleLineEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val saleId: String,
    val position: Int,
    val productId: Long?,
    val name: String,
    val sku: String?,
    val unitPriceMinor: Long,
    val quantity: Int,
    val taxName: String,
    val taxRateMilliPercent: Int,
    val netMinor: Long,
    val taxMinor: Long,
    val grossMinor: Long,
    val refundedQuantity: Int = 0,
)

/** Where a refund is in its lifecycle; stored by name in `refunds.status`. */
enum class RefundStatus {
    /** Written before the terminal is called. A refund still PENDING at the next app start was interrupted. */
    PENDING,

    /**
     * The terminal accepted the refund request. Adyen processes referenced refunds asynchronously, so this is not a
     * confirmation that the money was returned.
     */
    REQUESTED,

    /** The terminal rejected the request, or it never took effect (for example because the terminal is not set up). */
    FAILED,

    /** The outcome could not be established, for example because the app stopped mid-request. */
    UNKNOWN,
}

/**
 * A referenced refund (table `refunds`): a Terminal API reversal of an earlier payment.
 *
 * The payment can have been taken on this terminal (then [saleId] links it) or be identified only by the refund QR
 * code printed on its receipt. The row is inserted as [RefundStatus.PENDING] before the terminal is called. Amounts are
 * in minor units of [currency].
 */
@Entity(tableName = "refunds", indices = [Index("createdAt"), Index("saleId")])
data class RefundEntity(
    /** Random UUID generated by the app. */
    @PrimaryKey val id: String,
    /**
     * The local sale, when the refunded payment was taken on this terminal. It is not a foreign key: the refund stays in
     * history when its sale is pruned.
     */
    val saleId: String?,
    /** When the refund was started, in epoch milliseconds; history is ordered and pruned by it. */
    val createdAt: Long,
    /** The refund's own merchant reference, such as `R-260930-145811-VQ45`. */
    val merchantReference: String,
    /** POITransactionID of the payment being refunded. */
    val originalTransactionId: String,
    /** The original payment's POITransactionID time stamp, exactly as sent in the reversal request. */
    val originalTimestamp: String,
    /** Merchant reference of the original payment, shown on the refund receipt; null if unknown. */
    val originalReference: String?,
    /** ISO 4217 code of the original payment's currency. */
    val currency: String,
    /** Amount refunded. For a full refund this is the whole original amount. */
    val amountMinor: Long,
    /**
     * True for a full reversal, sent without an amount so Adyen refunds the whole payment (only offered when nothing was
     * refunded before); false for a partial refund of [amountMinor].
     */
    val full: Boolean,
    /** Lifecycle state; see [RefundStatus]. */
    val status: RefundStatus,
    /** The nexo ServiceID of the reversal request. */
    val serviceId: String? = null,
    /** Adyen's PSP reference for the refund, when the terminal returned one. */
    val pspReference: String? = null,
    /** Why the refund did not succeed, as the terminal worded it, for display; null when it did not say. */
    val message: String? = null,
    /**
     * JSON list of [io.github.astiskala.minimpos.core.receipt.CardReceiptLine] for the customer's card receipt;
     * null when none was sent.
     */
    val customerReceiptJson: String? = null,
    /** JSON list of [io.github.astiskala.minimpos.app.data.repo.RefundedLine] for an item refund; null for an amount or full refund. */
    val linesJson: String? = null,
    /**
     * True when this full reversal cancels a pre-authorisation (Adyen releases the held amount, or refunds it in full if
     * it was captured meanwhile) rather than refunding a sale. Added in database version 5.
     */
    @ColumnInfo(defaultValue = "0") val cancellation: Boolean = false,
    /**
     * Why the refund did not succeed when the app itself says so, worded on screen next to [message]; null otherwise.
     * Added in database version 10.
     */
    val reason: StoredReason? = null,
    /** Actual refund connection, persisted before sending; null before sending. */
    val context: PaymentContext? = null,
    /** Terminal acceptance time in epoch milliseconds; null before acceptance or when unavailable. */
    val processedAt: Long? = null,
)

/**
 * A sale with its lines, loaded together by Room (the DAO queries run in a transaction).
 *
 * @property sale The sale row.
 * @property lines Its lines in no particular order; use [sortedLines] for receipt order.
 */
data class SaleWithLines(
    @Embedded val sale: SaleEntity,
    @Relation(parentColumn = "id", entityColumn = "saleId") val lines: List<SaleLineEntity>,
) {
    /** [lines] in cart order (by [SaleLineEntity.position]). */
    val sortedLines: List<SaleLineEntity> get() = lines.sortedBy { it.position }
}
